# The URL the site will be built for
base_url = "https://yashrsharma44.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "material-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "xyblag"

# Blog details
description = "Happy space for scribbling down my thoughts, penning down my experiences with Software and Open Source."
title = "Yash Sharma"

generate_feed = true

taxonomies = [
  # You can enable/disable RSS
  {name = "categories", rss = true},
  {name = "tags", rss = true},
]

[extra]
# Put all your custom variables here
author = "yashrsharma44"
blog_menu = [
  {url = "$BASE_URL/categories", name = "Categories"},
  {url = "$BASE_URL/tags", name = "Tags"},
  {url = "$BASE_URL/about", name = "About"},
]
